theme = "darcula"

[editor]
line-number = "relative"
scrolloff = 99
cursorline = true
auto-save = true
auto-format = true
completion-replace = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = ["mode", "version-control", "spacer", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "spacer", "position-percentage", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = false
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.insert]
j = { k = "normal_mode" }
"C-backspace" = "delete_word_backward"
"C-space" = "completion"

[keys.normal]
"space" = { w = [":format", ":write"], q = ":quit", "=" = ":format" }
