theme = "poimandres_storm"

[editor]
line-number = "relative"
scrolloff = 99
cursorline = true
auto-format = true
completion-trigger-len = 1
color-modes = true
idle-timeout = 100

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = [
  "diagnostics",
  "selections",
  "spacer",
  "position-percentage",
  "file-type",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.insert]
j = { k = "normal_mode", q = "normal_mode" }
"C-backspace" = "delete_word_backward"
"C-space" = "completion"

[keys.normal]
"space" = { w = ":write", q = ":quit", "=" = ":format" }
"V" = "extend_line_below"
"X" = "extend_line_above"
