# tokens

attribute = { fg = "desaturatedBlue", modifiers = ["italic"] }
keyword = "brightMint"
"keyword.directive" = "brightMint"
"keyword.storage" = "desaturatedBlue"
"keyword.storage.modifier" = "lowerMint"
namespace = "lightBlue"
punctuation = "desaturatedBlue"
"punctuation.delimeter" = "desaturatedBlue"
operator = "desaturatedBlue"
special = "desaturatedBlue"
variable = "offWhite"
"variable.parameter" = { fg = "offWhite" }
"variable.builtin" = { fg = "lightBlue", modifiers = ["italic"] }
"variable.other.member" = "offWhite"
type = { fg = "#a6accdc0" }
"type.builtin" = { fg = "#a6accdc0" }
constructor = "lightBlue"
function = "lightBlue"
"function.method" = { fg = "lightBlue" }
tag = "brightMint"
comment = { fg = "#767c9dB0", modifiers = ["italic"] }
constant = "brightMint"
"constant.character.escape" = { fg = "lowerMint" }
"constant.numeric" = { fg = "brightMint" }
"constant.builtin" = { fg = "hotRed" }
label = { fg = "#a6accdc0" }
string = { fg = "brightMint" }


# Markup
"markup.heading" = { fg = "brightMint" }
"markup.bold" = { fg = "bluishGrayBrighter", modifiers = ["bold"] }
"markup.italic" = { fg = "bluishGrayBrighter", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["italic"] }

"markup.link.url" = { fg = "lightBlue", modifiers = ["underlined"] }
"markup.link.text" = { fg = "lightBlue", modifiers = ["underlined"] }
"markup.raw" = { fg = "lightBlue" }

# Version Control
"diff.plus" = "lowerMint"
"diff.minus" = "hotRed"
"diff.delta" = "lightBlue"


"ui.background" = { bg = "bg" }
"ui.background.separator" = { fg = "darkerGray" }
"ui.linenr" = "#767c9d50"
"ui.linenr.selected" = "offWhite"
"ui.cursor" = { bg = "gray", fg = "bg" }
"ui.cursor.match" = { bg = "focus" }
"ui.cursorline" = { bg = "#212434" }

"ui.popup" = { fg = "darkerGray" }

# Statusline
"ui.statusline" = { fg = "bg", bg = "bluishGrayBrighter" }
"ui.statusline.inactive" = { bg = "bg", fg = "bluishGray" }
"ui.statusline.normal" = { bg = "bg", fg = "desaturatedBlue" }
"ui.statusline.insert" = { bg = "bg", fg = "lightBlue" }
"ui.statusline.select" = { bg = "bg", fg = "hotRed" }

"ui.text" = "gray"
"ui.text.focus" = { fg = "offWhite", bg = "focus", modifiers = ["bold"] }
"ui.text.inactive" = "darkerGray"
"ui.virtual" = { fg = "#767c9dB0" }
"ui.virtual.indent-guide" = "#3d404e"

"ui.selection" = { bg = "focus" }
"ui.selection.primary" = { bg = "selection" }

"ui.menu" = { fg = "offWhite", bg = "bg" }
"ui.menu.selected" = { fg = "bg", bg = "gray" }
"ui.menu.scroll" = { fg = "white", bg = "bg" }

"diagnostic.hint" = { underline = { color = "lowerMint", style = "curl" } }
"diagnostic.info" = { underline = { color = "lightBlue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "brightYellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "hotRed", style = "curl" } }

hint = "lowerMint"
info = "lightBlue"
warning = "brightYellow"
error = "hotRed"

[palette]
brightYellow = "#fffac2"
brightMint = "#5DE4c7"
lowerMint = "#5fb3a1"
blueishGreen = "#42675A"
lowerBlue = "#89ddff"
lightBlue = "#ADD7FF"
desaturatedBlue = "#91B4D5"
bluishGrayBrighter = "#7390AA"
hotRed = "#d0679d"
pink = "#f087bd"
gray = "#a6accd"
darkerGray = "#767c9d"
bluishGray = "#506477"
focus = "#303340"
bg = "#1b1e28"
offWhite = "#e4f0fb"
selection = "#333851"
# selection = "#717cb425"
white = "#ffffff"
black = "#000000"
transparent = "#00000000"
